"use client"

import { useState, useEffect } from "react"
import { useRouter } from "next/navigation"
import { AppLayout } from "@/components/app-layout"
import { DiffViewer } from "@/components/diff-viewer"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Checkbox } from "@/components/ui/checkbox"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Badge } from "@/components/ui/badge"
import { ArrowLeft, GitCommit, Download, X } from "lucide-react"
import { toast } from "sonner"

interface FileChange {
  id: string
  path: string
  language: string
  additions: number
  deletions: number
  selected: boolean
  original: string
  modified: string
}

export default function DiffPage() {
  const router = useRouter()
  const [commitMessage, setCommitMessage] = useState("feat: Add user authentication functionality")
  const [selectedFile, setSelectedFile] = useState<string>("1")
  const [isCommitting, setIsCommitting] = useState(false)
  const [fileChanges, setFileChanges] = useState<FileChange[]>([])

  // Load generated code from session storage or use mock data
  useEffect(() => {
    const generatedCode = sessionStorage.getItem("generated-code")
    const language = sessionStorage.getItem("code-language") || "python"

    if (generatedCode) {
      // Create a file change from generated code
      const fileName = `src/generated.${language === "python" ? "py" : language === "javascript" ? "js" : "ts"}`
      const lines = generatedCode.split("\n").length
      setFileChanges([
        {
          id: "1",
          path: fileName,
          language: language,
          additions: lines,
          deletions: 0,
          selected: true,
          original: "",
          modified: generatedCode,
        },
      ])
      setCommitMessage(`feat: Add ${fileName.split("/").pop()} generated by AI`)
    } else {
      // Use mock data if no generated code
      setFileChanges(mockFileChanges)
    }
  }, [])

  // Mock file changes for demo
  const mockFileChanges: FileChange[] = [
    {
      id: "1",
      path: "src/auth.py",
      language: "python",
      additions: 45,
      deletions: 12,
      selected: true,
      original: `def login():
    pass

def logout():
    pass`,
      modified: `from flask import session, redirect, url_for
from werkzeug.security import check_password_hash

def login(email, password):
    """
    Authenticate user with email and password.
    Returns user object if successful, None otherwise.
    """
    user = User.query.filter_by(email=email).first()
    
    if user and check_password_hash(user.password_hash, password):
        session['user_id'] = user.id
        return user
    
    return None

def logout():
    """
    Log out the current user by clearing the session.
    """
    session.clear()
    return redirect(url_for('login'))`,
    },
    {
      id: "2",
      path: "src/models.py",
      language: "python",
      additions: 23,
      deletions: 5,
      selected: true,
      original: `class User:
    pass`,
      modified: `from datetime import datetime
from werkzeug.security import generate_password_hash

class User(db.Model):
    """User model for authentication."""
    
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(255), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def set_password(self, password):
        """Hash and set the user password."""
        self.password_hash = generate_password_hash(password)
    
    def __repr__(self):
        return f'<User {self.username}>'`,
    },
    {
      id: "3",
      path: "tests/test_auth.py",
      language: "python",
      additions: 67,
      deletions: 0,
      selected: true,
      original: "",
      modified: `import pytest
from src.auth import login, logout
from src.models import User

def test_login_success(app, db):
    """Test successful login with valid credentials."""
    user = User(email='test@example.com', username='testuser')
    user.set_password('password123')
    db.session.add(user)
    db.session.commit()
    
    result = login('test@example.com', 'password123')
    assert result is not None
    assert result.email == 'test@example.com'

def test_login_invalid_password(app, db):
    """Test login fails with invalid password."""
    user = User(email='test@example.com', username='testuser')
    user.set_password('password123')
    db.session.add(user)
    db.session.commit()
    
    result = login('test@example.com', 'wrongpassword')
    assert result is None

def test_logout(app):
    """Test logout clears session."""
    with app.test_client() as client:
        with client.session_transaction() as session:
            session['user_id'] = 1
        
        response = logout()
        assert response.status_code == 302`,
    },
  ]

  const toggleFileSelection = (fileId: string) => {
    setFileChanges((prev) => prev.map((file) => (file.id === fileId ? { ...file, selected: !file.selected } : file)))
  }

  const selectedFileData = fileChanges.find((f) => f.id === selectedFile)
  const totalAdditions = fileChanges.reduce((sum, file) => (file.selected ? sum + file.additions : sum), 0)
  const totalDeletions = fileChanges.reduce((sum, file) => (file.selected ? sum + file.deletions : sum), 0)
  const selectedCount = fileChanges.filter((f) => f.selected).length

  const handleCommit = async () => {
    if (!commitMessage.trim()) {
      toast.error("Please enter a commit message")
      return
    }

    if (selectedCount === 0) {
      toast.error("Please select at least one file to commit")
      return
    }

    setIsCommitting(true)

    // Simulate commit process
    await new Promise((resolve) => setTimeout(resolve, 1500))

    toast.success(`Successfully committed ${selectedCount} file(s)`)
    setIsCommitting(false)
    router.push("/agent")
  }

  return (
    <AppLayout>
      <div className="flex flex-col h-full">
        <div className="border-b bg-card px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button variant="ghost" size="sm" onClick={() => router.back()}>
                <ArrowLeft className="h-4 w-4 mr-2" />
                Back
              </Button>
              <div>
                <h1 className="text-xl font-semibold">Review Changes</h1>
                <p className="text-sm text-muted-foreground">
                  {selectedCount} file(s) selected • +{totalAdditions} -{totalDeletions}
                </p>
              </div>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm">
                <Download className="h-4 w-4 mr-2" />
                Download Patch
              </Button>
              <Button variant="outline" size="sm" onClick={() => router.back()}>
                <X className="h-4 w-4 mr-2" />
                Discard
              </Button>
              <Button size="sm" onClick={handleCommit} disabled={isCommitting || selectedCount === 0}>
                <GitCommit className="h-4 w-4 mr-2" />
                {isCommitting ? "Committing..." : "Commit Changes"}
              </Button>
            </div>
          </div>
        </div>

        <div className="flex-1 flex overflow-hidden">
          <div className="w-56
           border-r bg-card flex flex-col">
            <div className="p-4 border-b">
              <h2 className="text-sm font-semibold mb-3">Commit Message</h2>
              <Textarea
                value={commitMessage}
                onChange={(e) => setCommitMessage(e.target.value)}
                placeholder="Enter commit message..."
                className="min-h-[100px] resize-none text-sm"
              />
            </div>

            <div className="p-4 border-b">
              <h2 className="text-sm font-semibold mb-3">Changed Files ({fileChanges.length})</h2>
            </div>

            <ScrollArea className="flex-1">
              <div className="p-4 space-y-2">
                {fileChanges.map((file) => (
                  <button
                    key={file.id}
                    onClick={() => setSelectedFile(file.id)}
                    className={`w-full text-left p-3 rounded-lg transition-colors hover:bg-accent ${
                      selectedFile === file.id ? "bg-accent" : ""
                    }`}
                  >
                    <div className="flex items-start gap-2">
                      <Checkbox
                        checked={file.selected}
                        onCheckedChange={() => toggleFileSelection(file.id)}
                        onClick={(e) => e.stopPropagation()}
                        className="mt-0.5"
                      />
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium truncate">{file.path}</p>
                        <div className="flex items-center gap-2 mt-1">
                          <Badge
                            variant="outline"
                            className="text-xs bg-green-500/10 text-green-500 border-green-500/20"
                          >
                            +{file.additions}
                          </Badge>
                          {file.deletions > 0 && (
                            <Badge variant="outline" className="text-xs bg-red-500/10 text-red-500 border-red-500/20">
                              -{file.deletions}
                            </Badge>
                          )}
                        </div>
                      </div>
                    </div>
                  </button>
                ))}
              </div>
            </ScrollArea>
          </div>

          <div className="flex-1 flex flex-col overflow-hidden">
            {selectedFileData ? (
              <>
                <div className="border-b bg-card px-6 py-3">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-sm font-medium">{selectedFileData.path}</p>
                      <p className="text-xs text-muted-foreground">
                        {selectedFileData.additions} additions, {selectedFileData.deletions} deletions
                      </p>
                    </div>
                    <Badge variant="secondary">{selectedFileData.language}</Badge>
                  </div>
                </div>

                <div className="flex-1 overflow-hidden p-4">
                  <DiffViewer
                    original={selectedFileData.original}
                    modified={selectedFileData.modified}
                    language={selectedFileData.language}
                    fileName={selectedFileData.path}
                    additions={selectedFileData.additions}
                    deletions={selectedFileData.deletions}
                    height="calc(100vh - 250px)"
                  />
                </div>
              </>
            ) : (
              <div className="flex-1 flex items-center justify-center text-muted-foreground">
                <p>Select a file to view changes</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </AppLayout>
  )
}
